run_name: "middle_dutch_compet"
output_dir: "results"
device: "cpu"
use_wandb: true
wandb_project: "HTR-comparison" 

data:
  test: "/home/tmoins/Documents/WPC1/image_matching/middle_dutch/mss1/img/"

tasks:
  line:
    type: YoloLine
    config:
      model_path: "src/tasks/line/models/yolo26s_line_640px_16bs_50e.pt"
      img_size: 640
      batch_size: 4
      text_direction: "horizontal-lr"