run_name: "layout_yolo11s_comparison"
output_dir: "results"
device: "cpu"
use_wandb: true
wandb_project: "LA-comparison"
save_image: true


data:
  test: "../data/manifests_test_french/alto"

tasks:
  layout:
    type: YoloLayout
    config:
      model_path: "src/tasks/layout/LA-training/catmus_seg_s_16_10/weights/best.pt"
      
      img_size: 640
      text_direction: "horizontal-lr"