_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
batch_size:
    value: 16
corpus_path:
    value: null
data:
    value: catmus_seg
data_path:
    value: ../data_yolo/medieval-segmentation-yolo/config.yaml
epochs:
    value: 10
img_size:
    value: 640
model_path:
    value: LA-training/catmus_seg_s_16_10/weights/best.pt
name:
    value: catmus_seg_s_16_10
pretrained_w:
    value: yolo11s
training_mode:
    value: restricted
