run_name: "catmus_cheater_yolo_line"
output_dir: "results"
device: "cpu"
use_wandb: true
wandb_project: "icdar-htr-competition-2026"

data:
  test: "../data/cmmhwr26_minitest"

tasks:
  layout: 
    type: YoloLayout
    config:
      model_path: "src/tasks/layout/LA-training/catmus_seg_s_16_10/weights/best.pt"
      img_size: 640

  line:
    type: YoloLine
    config:
      model_path: "src/tasks/line/models/LINES-bbox_YOLOv11n.pt"
      text_direction: "horizontal-lr"
      batch_size: 4
      img_size: 640
  htr:
    type: KrakenHTR
    config:
      use_metadata: true
      model_path: "src/tasks/htr/models/catmus-medieval-1.6.0.mlmodel"