run_name: "yolo26_seg_line_chahan"
output_dir: "results"
device: "cpu"
use_wandb: true
wandb_project: "LS-comparison"

data:
  train: "../data/data_yolo/medieval-segmentation-yolo_lines_polygon/config_serveur.yaml"
  test: "../data/manifests_test_french/alto"

tasks:
  line: 
    type: YoloLine
    config:
      model_path: "src/tasks/line/models/LINES-SEG.pt"
      pretrained_w: "src/tasks/line/models/yolo26n.pt"
      img_size: 640
      batch_size: 16
      epochs: 10

      text_direction: "horizontal-lr"


