run_name: "Qwen_2B_line_level_cheater"
output_dir: "results"
device: "cuda"
use_wandb: true
wandb_project: "icdar-htr-competition-2026"
save_image: true

data:
  test: "../data/cmmhwr26_minitest"

tasks:
  layout: 
    type: YoloLayout
    config:
      model_path: "src/tasks/layout/models/yolo26s_layout_640px_16bs_50e.pt"
      img_size: 640

  line:
    type: YoloLine
    config:
      model_path: "src/tasks/line/models/LINES-SEG.pt"
      img_size: 640
      batch_size: 4
      text_direction: "horizontal-lr"
  htr:
    type: VLMLineHTR
    config:
      use_metadata: true
      model_name: "small-models-for-glam/Qwen3-VL-2B-catmus"
      base_model: "Qwen/Qwen3-VL-2B-Instruct"
      device_map: "auto"
      max_new_tokens: 128
      prompt: "Transcribe the text from this manuscript line. Do not translate, modernize or standardize the text. 
        For example, if the transcription is using 'ſ' instead of 's' or 'а' instead of 'a', keep it that way.
        Do not include any other words or separator in your response."