run_name: "churro_multiline"
output_dir: "results"
device: "cuda"
use_wandb: false
wandb_project: "icdar-htr-competition-2026"
save_image: true

data:
  train: "../data/ICDAR_Competition/train"
  valid: "../data/ICDAR_Competition/valid"
  test: "../data/ICDAR_Competition/test/"

tasks:
  htr:
    type: VLMMultiLineHTR
    config:
      use_metadata: true
      model_name: stanford-oval/churro-3B
      use_lora_adapter: true
      max_lines: 10
      max_new_tokens: 1024 #128
      line_batch_size: 1
      use_4bit: true
      lora_r: 16
      lora_dropout: 0
      max_seq_length: 2048 #512
      train_batch_size: 1
      gradient_accumulation_steps: 1
      warmup_ratio: 0.1
      epochs: 1
      learning_rate: 0.0001
      weight_decay: 0.01
      dataset_num_proc: 4
      prompt: > 
        You are a paleographer specializing in medieval languages.
        Follow these instructions:

        1. You will be provided with a series of line images from a scanned document.

        2. Perform transcription on the text from these images, line by line.

        3. If you encounter any non-text elements, simply skip them without attempting to describe them.

        4. Do not translate, modernize or standardize the text. 
        For example, if the transcription is using "ſ" instead of "s" or "а" instead of "a", keep it that way.

        5. Insert a newline character between each line of text output. Do not include any other words or separator in your response.

        Remember, your goal is to accurately transcribe the text from the scanned images as much as possible. 
