run_name: "Qwen3.5_4B"
output_dir: "results"
device: "cuda"
use_wandb: true
wandb_project: "icdar-htr-competition-2026"
save_image: true

data:
  train: "../data/ICDAR_Competition/train"
  valid: "../data/ICDAR_Competition/valid"
  test: "../data/ICDAR_Competition/test"

tasks:
  htr:
    type: VLMLineHTR
    config:
      use_metadata: true
      model_name: 'Qwen/Qwen3.5-4B'
      device_map: "auto"
      max_new_tokens: 128
      line_batch_size: 8
      max_pixels: 401408

      # LoRA
      use_4bit: false
      use_8bit: true
      lora_r: 64
      lora_dropout: 0
      use_rlora: false
      max_seq_length: 512
      train_batch_size: 8
      gradient_accumulation_steps: 2
      warmup_ratio: 0.01
      epochs: 2

      # lr 
      learning_rate: 1.0e-5
      weight_decay: 0.02
      dataset_num_proc: 4
      prompt: >
        Transcribe the handwritten text in this line image.
        {conventions}
        Output ONLY the transcription.
