run_name: "Qwen8B_linelvl"
output_dir: "results"
device: "cuda"
use_wandb: true
wandb_project: "icdar-htr-competition-2026"
save_image: true

data:
  test: "../data/ICDAR_Competition/test"

tasks:
  htr:
    type: VLMLineHTR
    config:
      use_metadata: true
      model_name: "small-models-for-glam/Qwen3-VL-8B-catmus"
      base_model: "Qwen/Qwen3-VL-8B-Instruct"
      device_map: "auto"
      max_new_tokens: 128
      prompt: "Transcribe the text from this manuscript line. Do not translate, modernize or standardize the text. 
        For example, if the transcription is using 'ſ' instead of 's' or 'а' instead of 'a', keep it that way.
        Do not include any other words or separator in your response."